-- =============================================
-- بيانات موقع TechCompare IQ لعام 2026
-- صُممت لتطبيقها مباشرة في Supabase SQL Editor
-- =============================================

-- تفريغ البيانات السابقة إذا أردت (اختياري)
-- TRUNCATE TABLE products CASCADE;
-- TRUNCATE TABLE offers CASCADE;

INSERT INTO products (category, name, brand, price_usd, price_iqd, features, full_specs, rating, tag, bg_color, image_url, type, is_offer, offer_discount)
VALUES
('ios', 'iPhone 17 Pro Max', 'Apple', 1199, 1822480, '["شريحة A19 Pro", "كاميرا 48MP رباعية بصرية", "شاشة 6.9 بوصة ProMotion", "تصميم تيتانيوم من الجيل الثاني"]'::jsonb, '{"الشاشة": "6.9\" Super Retina XDR OLED 120Hz", "المعالج": "A19 Pro (3nm)", "الرام": "12GB", "التخزين": "256GB / 512GB / 1TB / 2TB", "البطارية": "5000 mAh", "الكاميرا": "48MP رئيسية + 48MP واسعة + 48MP زووم 5x + 12MP تيليفوتو", "النظام": "iOS 20"}'::jsonb, 4.9, 'جديد', 'bg-gradient-to-br from-gray-800 to-black', '/images/products/iphone17-promax.jpg', 'سلسلة Pro', true, 'وفر 50$'),
('ios', 'iPhone 17 Pro', 'Apple', 999, 1518480, '["شريحة A19 Pro", "كاميرا 48MP", "شاشة 6.3 بوصة ProMotion الذكية", "هيكل تيتانيوم متين"]'::jsonb, '{"الشاشة": "6.3\" Super Retina XDR OLED 120Hz", "المعالج": "A19 Pro (3nm)", "الرام": "12GB", "التخزين": "256GB / 512GB / 1TB", "البطارية": "4000 mAh", "الكاميرا": "48MP + 48MP + 48MP", "النظام": "iOS 20"}'::jsonb, 4.8, 'الأكثر مبيعاً', 'bg-gradient-to-br from-gray-800 to-black', '/images/products/iphone17-pro.jpg', 'سلسلة Pro', false, ''),
('ios', 'iPhone 17 Plus', 'Apple', 899, 1366480, '["شريحة A18 Bionic", "كاميرا مزدوجة 48MP", "شاشة 6.7 بوصة", "بطارية تدوم يومين"]'::jsonb, '{"الشاشة": "6.7\" Super Retina XDR OLED 60Hz", "المعالج": "A18 Bionic (3nm)", "الرام": "8GB", "التخزين": "128GB / 256GB / 512GB", "البطارية": "4800 mAh", "الكاميرا": "48MP + 12MP", "النظام": "iOS 20"}'::jsonb, 4.7, '', 'bg-gradient-to-br from-gray-800 to-black', '/images/products/iphone17-plus.jpg', 'السلسلة العادية', false, ''),
('ios', 'iPhone 17', 'Apple', 799, 1214480, '["شريحة A18 Bionic", "نظام كاميرات متطور 48MP", "شاشة 6.1 بوصة", "مقاومة فائقة للماء والغبار"]'::jsonb, '{"الشاشة": "6.1\" Super Retina XDR OLED 60Hz", "المعالج": "A18 Bionic (3nm)", "الرام": "8GB", "التخزين": "128GB / 256GB / 512GB", "البطارية": "3800 mAh", "الكاميرا": "48MP + 12MP", "النظام": "iOS 20"}'::jsonb, 4.8, 'قيمة ممتازة', 'bg-gradient-to-br from-gray-800 to-black', '/images/products/iphone17.jpg', 'السلسلة العادية', false, ''),
('ios', 'iPhone 16 Pro Max', 'Apple', 1099, 1670480, '["شريحة A18 Pro", "كاميرا 48MP زووم 5x", "شاشة 6.9 بوصة", "هيكل تيتانيوم"]'::jsonb, '{"الشاشة": "6.9\" Super Retina XDR OLED 120Hz", "المعالج": "A18 Pro (3nm)", "الرام": "8GB", "التخزين": "256GB / 512GB / 1TB", "البطارية": "4676 mAh", "الكاميرا": "48MP + 48MP + 12MP", "النظام": "iOS 19 المستحدث"}'::jsonb, 4.8, 'تخفيض', 'bg-gradient-to-br from-gray-800 to-black', '/images/products/iphone16-promax.jpg', 'سلسلة Pro', true, '100$'),
('android', 'Samsung Galaxy S26 Ultra', 'Samsung', 1299, 1974480, '["معالج Snapdragon 8 Gen 4", "كاميرا 200MP مع تقنيات AI", "شاشة 6.8 بوصة Dynamic AMOLED 2X", "قلم S Pen مدمج وتصميم تيتانيوم"]'::jsonb, '{"الشاشة": "6.8\" Dynamic AMOLED 2X 144Hz 3200nit", "المعالج": "Snapdragon 8 Gen 4", "الرام": "16GB", "التخزين": "256GB / 512GB / 1TB", "البطارية": "5500 mAh", "الكاميرا": "200MP + 50MP + 50MP + 12MP", "النظام": "Android 16 - OneUI 8.1"}'::jsonb, 4.9, 'الأقوى عالمياً', 'bg-gradient-to-br from-gray-800 to-black', '/images/products/s26-ultra.jpg', 'الفئة الرائدة', true, 'سماعات هدية'),
('android', 'Samsung Galaxy S26+', 'Samsung', 999, 1518480, '["معالج Snapdragon 8 Gen 4", "كاميرا 50MP معززة بالذكاء الاصطناعي", "شاشة 6.7 بوصة", "بطارية عملاقة 5000mAh"]'::jsonb, '{"الشاشة": "6.7\" Dynamic AMOLED 2X 120Hz", "المعالج": "Snapdragon 8 Gen 4", "الرام": "12GB", "التخزين": "256GB / 512GB", "البطارية": "5000 mAh", "الكاميرا": "50MP + 12MP + 10MP", "النظام": "Android 16 - OneUI 8.1"}'::jsonb, 4.8, '', 'bg-gradient-to-br from-gray-800 to-black', '/images/products/s26-plus.jpg', 'الفئة الرائدة', false, ''),
('android', 'Xiaomi 16 Pro', 'Xiaomi', 899, 1366480, '["معالج Snapdragon 8 Gen 4", "كاميرا Leica 50MP مستشعر 1 بوصة", "شاشة 6.73\" 120Hz AMOLED", "شحن سريع خارق 120W"]'::jsonb, '{"الشاشة": "6.73\" LTPO AMOLED 144Hz 4000nit", "المعالج": "Snapdragon 8 Gen 4", "الرام": "12GB / 16GB", "التخزين": "256GB / 512GB / 1TB", "البطارية": "5300 mAh", "الكاميرا": "50MP + 50MP + 50MP Leica", "النظام": "HyperOS 2.0 (Android 16)"}'::jsonb, 4.7, 'كاميرا خرافية', 'bg-gradient-to-br from-gray-800 to-black', '/images/products/xiaomi16-pro.jpg', 'الفئة الرائدة', false, ''),
('android', 'Google Pixel 10 Pro XL', 'Google', 1099, 1670480, '["شريحة Google Tensor G5 المعززة بالذكاء الاصطناعي", "أفضل كاميرا لالتقاط الصور في العالم", "شاشة 6.8\" Super Actua", "7 سنوات من التحديثات"]'::jsonb, '{"الشاشة": "6.8\" LTPO OLED 120Hz", "المعالج": "Tensor G5 (3nm)", "الرام": "16GB", "التخزين": "256GB / 512GB / 1TB", "البطارية": "5100 mAh", "الكاميرا": "50MP + 48MP + 48MP", "النظام": "Android 16 النقي"}'::jsonb, 4.8, 'ميزات AI حصرية', 'bg-gradient-to-br from-gray-800 to-black', '/images/products/pixel10-proxl.jpg', 'الفئة الرائدة', false, ''),
('android', 'OnePlus 14', 'OnePlus', 799, 1214480, '["معالج Snapdragon 8 Gen 4", "شاشة 6.82\" AMOLED 120Hz", "بطارية 5500mAh وشحن 100W", "كاميرات Hasselblad 50MP"]'::jsonb, '{"الشاشة": "6.82\" LTPO AMOLED 120Hz 4500nit", "المعالج": "Snapdragon 8 Gen 4", "الرام": "12GB / 16GB / 24GB", "التخزين": "256GB / 512GB / 1TB", "البطارية": "5500 mAh", "الكاميرا": "50MP + 64MP + 48MP", "النظام": "OxygenOS 16 (Android 16)"}'::jsonb, 4.7, 'الأسرع شحناً', 'bg-gradient-to-br from-gray-800 to-black', '/images/products/oneplus14.jpg', 'قاتل الفلاج شيب', false, ''),
('laptops', 'MacBook Pro 16" (M5 Max)', 'Apple', 3499, 5318480, '["معالج Apple M5 Max الأقوى عالمياً", "شاشة Liquid Retina XDR 120Hz", "ذاكرة عشوائية تصل إلى 128GB", "بطارية تدوم حتى 25 ساعة"]'::jsonb, '{"الشاشة": "16.2\" Liquid Retina XDR (Mini-LED) 120Hz", "المعالج": "Apple M5 Max (40-core GPU)", "الرام": "64GB / 128GB", "التخزين": "1TB / 2TB / 4TB SSD", "البطارية": "100Wh", "الوزن": "2.14 kg", "المنافذ": "3x Thunderbolt 5, HDMI 2.1, SDXC"}'::jsonb, 5.0, 'للمحترفين', 'bg-gradient-to-br from-gray-800 to-black', '/images/products/macbook-pro-16-m5.jpg', 'لابتوب محمول للعمل الشاق', false, ''),
('laptops', 'MacBook Air 15" (M5)', 'Apple', 1299, 1974480, '["معالج Apple M5 فائق النحافة والكفاءة", "شاشة Liquid Retina قياس 15.3 بوصة", "تصميم بدون مراوح", "بطارية تدوم طويلاً"]'::jsonb, '{"الشاشة": "15.3\" Liquid Retina IPS", "المعالج": "Apple M5 (10-core GPU)", "الرام": "16GB / 24GB", "التخزين": "512GB / 1TB SSD", "البطارية": "66.5Wh", "الوزن": "1.51 kg", "المنافذ": "2x Thunderbolt 4, MagSafe 3"}'::jsonb, 4.8, 'الأنحف', 'bg-gradient-to-br from-gray-800 to-black', '/images/products/macbook-air-15-m5.jpg', 'لابتوب خفيف الوزن', false, ''),
('laptops', 'Dell XPS 16 (2026)', 'Dell', 2299, 3494480, '["معالج Intel Core Ultra 9 (الجيل الثاني)", "شاشة 4K OLED تعمل باللمس", "كرت شاشة RTX 5070", "تصميم زجاجي وألمنيوم مستقبلي"]'::jsonb, '{"الشاشة": "16.3\" 4K+ OLED Touch 120Hz", "المعالج": "Intel Core Ultra 9 285H", "الرام": "32GB LPDDR5x", "التخزين": "1TB / 2TB PCIe Gen5", "بطاقة الشاشة": "NVIDIA GeForce RTX 5070 8GB", "الوزن": "2.13 kg", "النظام": "Windows 12"}'::jsonb, 4.8, 'تصميم مستقبلي', 'bg-gradient-to-br from-gray-800 to-black', '/images/products/dell-xps-16.jpg', 'لابتوب فخم للأعمال والتصميم', false, ''),
('laptops', 'Asus ROG Zephyrus G16 (2026)', 'Asus', 2499, 3798480, '["معالج AMD Ryzen AI 9", "كرت شاشة RTX 5080 لأقصى أداء ألعاب", "شاشة 240Hz OLED", "تصميم فائق النحافة من الألمنيوم 1.85 كجم"]'::jsonb, '{"الشاشة": "16\" 2.5K OLED 240Hz 0.2ms", "المعالج": "AMD Ryzen AI 9 HX 370", "الرام": "32GB LPDDR5X", "التخزين": "2TB NVMe SSD", "بطاقة الشاشة": "NVIDIA GeForce RTX 5080 16GB", "الوزن": "1.85 kg", "النظام": "Windows 12 Home"}'::jsonb, 4.9, 'أفضل لابتوب ألعاب', 'bg-gradient-to-br from-gray-800 to-black', '/images/products/rog-zephyrus-g16.jpg', 'لابتوب ألعاب محمول', false, ''),
('laptops', 'Lenovo ThinkPad X1 Carbon Gen 14', 'Lenovo', 1899, 2886480, '["معالج Intel Core Ultra 7 مع ميزات ذكاء اصطناعي", "وزن خفيف جداً يبلغ 1.08 كجم", "شاشة 14\" 2.8K OLED", "كيبورد ThinkPad الأسطوري وتصميم متين"]'::jsonb, '{"الشاشة": "14\" 2.8K OLED 120Hz", "المعالج": "Intel Core Ultra 7 265U", "الرام": "32GB LPDDR5X", "التخزين": "1TB SSD", "البطارية": "57Wh", "الوزن": "1.08 kg", "النظام": "Windows 12 Pro"}'::jsonb, 4.9, 'للأعمال', 'bg-gradient-to-br from-gray-800 to-black', '/images/products/thinkpad-x1.jpg', 'لابتوب خاص بالأعمال', false, ''),
('pcs', 'Alienware Aurora R18', 'Dell', 3999, 6078480, '["معالج Intel Core i9-15900K", "بطاقة رسوميات RTX 5090", "تبريد مائي متقدم Cyro-Tech", "هيكل بتصميم فضائي متطور وإضاءة RGB شاملة"]'::jsonb, '{"المعالج": "Intel Core i9-15900K 24-Core", "الرام": "64GB DDR5 7200MHz", "التخزين": "4TB NVMe M.2 PCIe 5.0", "بطاقة الشاشة": "NVIDIA GeForce RTX 5090 32GB", "الماذربورد": "Z890 Custom", "مزود الطاقة": "1500W 80+ Platinum", "النظام": "Windows 12 Pro"}'::jsonb, 4.9, 'الوحش المطلق', 'bg-gradient-to-br from-gray-800 to-black', '/images/products/alienware-r18.jpg', 'كمبيوتر ألعاب مكتبي مجنون', false, ''),
('pcs', 'ROG Strix G35CA (2026)', 'Asus', 2799, 4254480, '["معالج AMD Ryzen 9 9950X", "بطاقة رسوميات RTX 5080", "تبريد هوائي ومائي هجين", "سهولة الترقية وتصميم رياضي"]'::jsonb, '{"المعالج": "AMD Ryzen 9 9950X 16-Core", "الرام": "32GB DDR5 6400MHz", "التخزين": "2TB NVMe M.2", "بطاقة الشاشة": "NVIDIA GeForce RTX 5080 16GB", "الماذربورد": "X870E ROG Strix", "مزود الطاقة": "1000W 80+ Gold", "النظام": "Windows 12 Home"}'::jsonb, 4.8, '', 'bg-gradient-to-br from-gray-800 to-black', '/images/products/rog-strix-pc.jpg', 'كمبيوتر ألعاب عالي الأداء', false, ''),
('pcs', 'HP OMEN 45L', 'HP', 2199, 3342480, '["معالج Intel Core i7-15700K", "بطاقة رسوميات RTX 5070 Ti", "حجرة تبريد مائي مستقلة (OMEN Cryo Chamber)", "زجاج مقوى من الجانبين وتصميم أنيق"]'::jsonb, '{"المعالج": "Intel Core i7-15700K 20-Core", "الرام": "32GB DDR5 6000MHz Kingston Fury", "التخزين": "2TB WD Black PCIe 4.0", "بطاقة الشاشة": "NVIDIA GeForce RTX 5070 Ti 16GB", "الماذربورد": "Z890 OMEN Custom", "مزود الطاقة": "850W 80+ Gold", "النظام": "Windows 12"}'::jsonb, 4.7, 'تبريد ممتاز', 'bg-gradient-to-br from-gray-800 to-black', '/images/products/hp-omen-45l.jpg', 'كمبيوتر ألعاب', false, ''),
('monitors', 'Samsung Odyssey Neo G9 (2026) 57"', 'Samsung', 2499, 3798480, '["شاشة منحنية ضخمة 57 بوصة بدقة Dual UHD 8K", "معدل تحديث 240Hz", "تقنية Quantum Mini-LED بـ 4000 منطقة تعتيم", "دعم DisplayPort 2.1 و HDMI 2.1"]'::jsonb, '{"حجم الشاشة": "57 بوصة منحنية 1000R", "اللوحة": "Quantum Mini-LED VA", "الدقة": "7680 x 2160 (Dual UHD)", "معدل التحديث": "240Hz", "زمن الاستجابة": "1ms GTG", "السطوع": "2000 nits (HDR2000)", "المنافذ": "DP 2.1, 3x HDMI 2.1, USB Hub"}'::jsonb, 4.9, 'شاشة الأحلام', 'bg-gradient-to-br from-gray-800 to-black', '/images/products/odyssey-g9-57.jpg', 'شاشة ألعاب Ultra-Wide', false, ''),
('monitors', 'LG UltraGear OLED 32" 4K', 'LG', 1199, 1822480, '["شاشة 32 بوصة بدقة 4K وتقنية OLED", "معدل تحديث 240Hz (مع وضع 1080p بـ 480Hz)", "زمن استجابة خيالي 0.03ms", "الجيل الثالث من لوحات MLA OLED سطوع أعلى بنسبة 30%"]'::jsonb, '{"حجم الشاشة": "32 بوصة مسطحة", "اللوحة": "WOLED (MLA+) الجيل الثالث", "الدقة": "3840 x 2160 (4K UHD)", "معدل التحديث": "240Hz / 480Hz Dual Mode", "زمن الاستجابة": "0.03ms", "دعم": "G-Sync Compatible, FreeSync Premium Pro"}'::jsonb, 4.8, 'الأكثر طلباً للألعاب', 'bg-gradient-to-br from-gray-800 to-black', '/images/products/lg-ultragear-32-oled.jpg', 'شاشة ألعاب تنافسية وقصة', false, ''),
('monitors', 'Asus ProArt Display 27" 5K', 'Asus', 1499, 2278480, '["شاشة احترافية 27 بوصة بدقة 5K", "دقة ألوان متناهية ∆E < 1", "إضاءة Mini-LED", "معايرة ألوان هارداوير مدمجة"]'::jsonb, '{"حجم الشاشة": "27 بوصة مسطحة", "اللوحة": "IPS Mini-LED", "الدقة": "5120 x 2880 (5K)", "معدل التحديث": "120Hz", "تصحيح الألوان": "99% DCI-P3, 100% sRGB", "المنافذ": "Thunderbolt 4 (96W PD), HDMI 2.1"}'::jsonb, 4.9, 'للمصممين', 'bg-gradient-to-br from-gray-800 to-black', '/images/products/asus-proart-27.jpg', 'شاشة إنتاجية وصناعة محتوى', false, ''),
('accessories', 'AirPods Pro 3', 'Apple', 249, 378480, '["شريحة H3 جديدة لصوت مكاني ثوري", "عزل ضوضاء (ANC) أضعف مرتين أفضل", "علبة شحن تحتوي على شاشة صغيرة", "مستشعر قياس حرارة الجسم"]'::jsonb, '{"النوع": "سماعات أذن لاسلكية داخل الأذن", "نظام توجيه الصوت": "Spatial Audio مع تتبع حركة الرأس 2.0", "البطارية": "حتى 8 ساعات بشحنة واحدة / 36 مع العلبة", "االميزات": "عزل نشط, نمط شفافية التكيفي, قياس درجة الحرارة", "المنافذ": "USB-C / MagSafe"}'::jsonb, 4.9, 'الأحدث', 'bg-gradient-to-br from-gray-800 to-black', '/images/products/airpods-pro-3.jpg', 'سماعات أذن لاسلكية', false, ''),
('accessories', 'Samsung Galaxy Watch 8 Ultra', 'Samsung', 449, 682480, '["شاشة Micro-LED ساطعة جداً", "قياس ضغط الدم وتخطيط القلب المتقدم", "بطارية تدوم لأيام مع نظام تشغيل WearOS 6", "هيكل قوي من التيتانيوم وزجاج الياقوت"]'::jsonb, '{"الشاشة": "1.5\" Micro-LED", "المعالج": "Exynos W1100 (3nm)", "المستشعرات": "BioActive 3.0, ECG, Blood Pressure, Temperature, SpO2", "البطارية": "600 mAh", "مقاومة الماء": "10ATM / IP68 / MIL-STD-810H"}'::jsonb, 4.8, '', 'bg-gradient-to-br from-gray-800 to-black', '/images/products/galaxy-watch-8-ultra.jpg', 'ساعة ذكية للمحترفين الرياضيين', true, '20$'),
('accessories', 'Razer Viper V3 Pro (2026 Edition)', 'Razer', 150, 228000, '["وزن خفيف جداً يبلغ 52غرام", "مستشعر Focus Pro Gen-3 بدقة 40,000 DPI", "معدل إرسال لاسلكي 8000Hz (HyperPolling مدمج)", "أزرار بصرية للجيل الرابع للسرعة"]'::jsonb, '{"الوزن": "52 غرام", "المستشعر": "Razer Focus Pro 40K Optical", "السرعة القسوى": "750 IPS", "التسارع": "70G", "معدل التحديث": "8000 Hz لاسلكي", "البطارية": "حتى 100 ساعة"}'::jsonb, 4.9, 'للألعاب التنافسية', 'bg-gradient-to-br from-gray-800 to-black', '/images/products/razer-viper-v3-pro.jpg', 'ماوس ألعاب رياضي احترافي', false, '');

-- =============================================
-- إضافة عروض لعام 2026
INSERT INTO offers (title, desc_text, image_color, badge, time_left)
VALUES
('Galaxy S26 Ultra - عرض إطلاق', 'احصل على هاتف الذكاء الاصطناعي الأقوى لعام 2026 مع سماعات وقلم هدايا. الأقوى في الأداء والتصوير.', 'bg-gradient-to-r from-purple-900 to-indigo-900', 'حصرياً', 'ينتهي بعد 3 أيام'),
('تخفيضات Apple 2026', 'خصم 10% على جميع أجهزة MacBook Pro M5 الجديدة. ارفع إنتاجيتك إلى المستوى التالي.', 'bg-gradient-to-r from-gray-900 to-gray-700', 'تخفيض ضخم', 'أسبوع واحد فقط'),
('لابتوبات الجيل القادم', 'اشترِ لابتوب ألعاب معتمدة لعام 2026 بتقنية RTX 5000 واحصل على ماوس ولوحة مفاتيح احترافية.', 'bg-gradient-to-r from-red-900 to-red-700', 'عرض جيمرز', 'الكمية محدودة');

-- =============================================
-- تحديث الواجهة الرئيسية (Hero Content) لعام 2026
UPDATE hero_content SET 
  title = 'بوابة المستقبل 2026.. اختر الأفضل',
  subtitle = 'اكتشف وقارن أحدث ثورة في التكنولوجيا لعام 2026. من الهواتف الذكية الداعمة للذكاء الاصطناعي إلى الحواسيب الفائقة، التقنية في العراق بمستوى جديد تماماً.',
  cta_text = 'استكشف أجهزة 2026',
  badge_title = 'تريند السنة',
  badge_text = 'Apple M5 & Galaxy S26 وصلوا !!',
  badge_visible = true
WHERE id = 1;

-- =============================================
-- تحديث إعدادات الموقع لعام 2026
UPDATE site_settings SET 
  description = 'المنصة رقم 1 في العراق لمقارنة الأجهزة التقنية الذكية لعام 2026.',
  exchange_rate = 1520
WHERE id = 1;
