-- =============================================
-- تحديثات لعام 2026 : الدفعة الثانية (الساعات)
-- =============================================

-- تعديل قيود الجدول للسماح بالأقسام الجديدة
ALTER TABLE products DROP CONSTRAINT IF EXISTS products_category_check;
ALTER TABLE products ADD CONSTRAINT products_category_check CHECK (category IN ('android', 'ios', 'laptops', 'pcs', 'monitors', 'accessories', 'apple-watches', 'other-watches'));

INSERT INTO products (category, name, brand, price_usd, price_iqd, features, full_specs, rating, tag, bg_color, image_url, type, is_offer, offer_discount)
VALUES
('apple-watches', 'Apple Watch Ultra 3', 'Apple', 899, 1366480, '["شاشة MicroLED ساطعة 3000 شمعة", "قياس ضغط الدم والسكر بدون وخز", "مقاومة للماء حتى 100 متر وغوص احترافي", "بطارية تدوم 72 ساعة"]'::jsonb, '{"الشاشة": "1.92\" MicroLED Always-On", "المعالج": "S11 SiP (3nm)", "الهيكل": "تيتانيوم للطيران والفضاء", "المستشعرات": "قياس السكر، ضغط الدم، حرارة الجسم، تخطيط القلب", "البطارية": "حتى 72 ساعة (120 وضع توفير)", "الوزن": "61.4g", "النظام": "watchOS 13"}'::jsonb, 4.9, 'الأقوى', 'bg-gradient-to-br from-slate-100 to-slate-200', '/images/products/apple-watch-ultra-3.jpg', 'ساعة رياضية للمحترفين', true, 'سوار إضافي مجاني'),
('apple-watches', 'Apple Watch Series 11', 'Apple', 399, 606480, '["معالج S11 الجديد", "شاشة أنحف وحواف شبه معدومة", "مستشعر قياس ضغط الدم الذكي", "شحن سريع من 0 لـ 80% في 30 دقيقة"]'::jsonb, '{"الشاشة": "LTPO OLED Always-On 2500nits", "المعالج": "S11 SiP (3nm)", "الهيكل": "ألمنيوم معاد تدويره / ستانلس ستيل", "المستشعرات": "ضغط الدم، تخطيط القلب، تتبع النوم المتقدم", "البطارية": "حتى 24 ساعة", "الأحجام": "41mm & 45mm", "النظام": "watchOS 13"}'::jsonb, 4.8, 'الأكثر مبيعاً', 'bg-gradient-to-br from-slate-100 to-slate-200', '/images/products/apple-watch-series-11.jpg', 'ساعة ذكية يومية', false, ''),
('apple-watches', 'Apple Watch SE (Gen 3)', 'Apple', 249, 378480, '["معالج S10 سريع", "شاشة OLED أكبر بنسبة 20%", "تتبع الأنشطة الرياضية بدقة", "تصميم ألمنيوم خفيف"]'::jsonb, '{"الشاشة": "Retina OLED 1000nits", "المعالج": "S10 SiP (4nm)", "الهيكل": "ألمنيوم بلاستيك حيوي", "المستشعرات": "معدل نبضات القلب، اكتشاف السقوط والحوادث", "البطارية": "حتى 18 ساعة", "الأحجام": "40mm & 44mm", "النظام": "watchOS 13"}'::jsonb, 4.7, 'قيمة ممتازة', 'bg-gradient-to-br from-slate-100 to-slate-200', '/images/products/apple-watch-se-3.jpg', 'ساعة الفئة الاقتصادية', false, ''),
('other-watches', 'Samsung Galaxy Watch 8 Ultra', 'Samsung', 449, 682480, '["شاشة Micro-LED ساطعة جداً", "قياس ضغط الدم وتخطيط القلب المتقدم", "بطارية تدوم لأيام مع نظام تشغيل WearOS 6", "هيكل قوي من التيتانيوم وزجاج الياقوت"]'::jsonb, '{"الشاشة": "1.5\" Micro-LED", "المعالج": "Exynos W1100 (3nm)", "المستشعرات": "BioActive 3.0, ECG, Blood Pressure, Temperature, SpO2", "البطارية": "600 mAh", "مقاومة الماء": "10ATM / IP68 / MIL-STD-810H"}'::jsonb, 4.8, 'الرد الأقوى', 'bg-gradient-to-br from-slate-100 to-slate-200', '/images/products/galaxy-watch-8-ultra.jpg', 'ساعة ذكية للمحترفين الرياضيين', true, '20$'),
('other-watches', 'Samsung Galaxy Watch 8 Pro', 'Samsung', 349, 530480, '["معالج Exynos W1100 بتقنية 3nm", "إطار دوار كلاسيكي (Rotating Bezel)", "مستشعر BioActive 3.0 محسن للرياضة", "شاشة Super AMOLED بدقة فائقة التباين"]'::jsonb, '{"الشاشة": "1.47\" Super AMOLED 2000nits", "المعالج": "Exynos W1100 (3nm)", "الهيكل": "ستانلس ستيل فاخر", "المستشعرات": "قياس تكوين الجسم (BIA)، تخطيط القلب", "البطارية": "425 mAh (حتى 40 ساعة)", "النظام": "WearOS 6 - OneUI Watch"}'::jsonb, 4.8, 'الكلاسيكية الحديثة', 'bg-gradient-to-br from-slate-100 to-slate-200', '/images/products/galaxy-watch-8-pro.jpg', 'ساعة ذكية يومية', false, ''),
('other-watches', 'Huawei Watch Ultimate 2 (2026)', 'Huawei', 850, 1292000, '["هيكل من السائل المعدني الزركوني والألماس الأزرق", "دعم الاتصال عبر الأقمار الصناعية ثنائي الاتجاه", "غوص احترافي لعمق 120 متر", "بطارية خرافية تدوم 14 يوماً"]'::jsonb, '{"الشاشة": "1.5\" LTPO AMOLED", "الهيكل": "زجاج ياقوتي، سيراميك نانو السائل", "المستشعرات": "ECG، قاسي الشرايين، حساس العمق والحرارة", "البطارية": "أسبوعين شحنة كاملة", "مقاومة الماء": "ISO 22810 & EN13319 للغوص", "النظام": "HarmonyOS 5.0"}'::jsonb, 4.9, 'تحفة فنية', 'bg-gradient-to-br from-slate-100 to-slate-200', '/images/products/huawei-watch-ultimate-2.jpg', 'ساعة فاخرة للمغامرين', false, ''),
('other-watches', 'Xiaomi Watch S4 Pro', 'Xiaomi', 249, 378480, '["شاشة AMOLED بحواف منعدمة تماماً", "تصميم كلاسيكي بسوار جلدي قابل للتخصيص بضغطة زر", "دعم eSIM مكالماتمستقلة", "بطارية 10 أيام مع مستشعرات دقيقة"]'::jsonb, '{"الشاشة": "1.43\" AMOLED 1500nits", "المعالج": "Qualcomm Snapdragon W5+ Gen 2", "الهيكل": "ألمنيوم مقوى مقاوم للخدش", "المستشعرات": "GPS ثنائي النطاق، Bio-Tracker 5.0", "البطارية": "500 mAh", "النظام": "HyperOS 2.0 (WearOS 기반)"}'::jsonb, 4.7, 'أناقة وأداء', 'bg-gradient-to-br from-slate-100 to-slate-200', '/images/products/xiaomi-watch-s4-pro.jpg', 'ساعة متكاملة بسعر منافس', false, '');

